version: "3.5"

services:
  postgres:
    image: postgres:latest
    volumes:
      - eskoolportaldb:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile.dev
  #   volumes:
  #     - /app/node_modules
  #     - /app/.next/
  #     - .:/app
  #   ports:
  #     - 3000:3000
volumes:
  eskoolportaldb:
