-- AlterTable
ALTER TABLE "Exam" ALTER COLUMN "startDate" SET DATA TYPE DATE,
ALTER COLUMN "endDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Student" ALTER COLUMN "dateOfBirth" SET DATA TYPE DATE,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "joinDate" SET DATA TYPE DATE;
